# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

one:
  name: MyString
  number: 1
  description: MyString
  on_shelf: false
  price: 9.99
  product_category_id: 1

two:
  name: MyString
  number: 1
  description: MyString
  on_shelf: false
  price: 9.99
  product_category_id: 1
